name: task_management_app_1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  ionicons: 0.2.1
  firebase_core: 2.6.1
  firebase_auth: 4.2.8
  google_sign_in: 5.4.3
  flutter: 
    sdk: flutter
  flutterfire_cli: ^0.2.7
  firebase_core_web: ^2.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/Images/
    - assets/Icons/
  uses-material-design: true

