// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvGmyJKLgEySLGM5drRjvyCkwdAREUq8k',
    appId: '1:1079263788857:web:087d29603fbcba7fc0f2e8',
    messagingSenderId: '1079263788857',
    projectId: 'tugas-individu-884e7',
    authDomain: 'tugas-individu-884e7.firebaseapp.com',
    storageBucket: 'tugas-individu-884e7.appspot.com',
    measurementId: 'G-PZXQN7PJFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvGmyJKLgEySLGM5drRjvyCkwdAREUq8k',
    appId: '1:1079263788857:web:087d29603fbcba7fc0f2e8',
    messagingSenderId: '1079263788857',
    projectId: 'tugas-individu-884e7',
    storageBucket: 'tugas-individu-884e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvGmyJKLgEySLGM5drRjvyCkwdAREUq8k',
    appId: '1:1079263788857:web:087d29603fbcba7fc0f2e8',
    messagingSenderId: '1079263788857',
    projectId: 'tugas-individu-884e7',
    storageBucket: 'tugas-individu-884e7.appspot.com',
    androidClientId:
        '860614070882-5lp3ekhrhnkn3u6mbje10esoih14lbe6.apps.googleusercontent.com',
    iosClientId:
        '860614070882-ognnjc3cvrnfmcdr34iass400cmnrthv.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvGmyJKLgEySLGM5drRjvyCkwdAREUq8k',
    appId: '1:1079263788857:web:087d29603fbcba7fc0f2e8',
    messagingSenderId: '1079263788857',
    projectId: 'tugas-individu-884e7',
    storageBucket: 'tugas-individu-884e7.appspot.com',
    androidClientId:
        '860614070882-5lp3ekhrhnkn3u6mbje10esoih14lbe6.apps.googleusercontent.com',
    iosClientId:
        '860614070882-ognnjc3cvrnfmcdr34iass400cmnrthv.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp1',
  );
}
