// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm8Bz4T5eUzv9Oe9R6H5w_mrOI1i3W-fc',
    appId: '1:860614070882:web:d5b5c0cea3c86aaef0b73b',
    messagingSenderId: '860614070882',
    projectId: 'task-management-apps-1',
    authDomain: 'task-management-apps-1.firebaseapp.com',
    storageBucket: 'task-management-apps-1.appspot.com',
    measurementId: 'G-7CS73TBNFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNsx_8ewn6jshs_TsUnBzqWHdoGm7cGbE',
    appId: '1:860614070882:android:762ab29513bd0975f0b73b',
    messagingSenderId: '860614070882',
    projectId: 'task-management-apps-1',
    storageBucket: 'task-management-apps-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbx_dFjmiWCcDizO_eNjJRhsL3bJ6OrCM',
    appId: '1:860614070882:ios:7025b23e509415cef0b73b',
    messagingSenderId: '860614070882',
    projectId: 'task-management-apps-1',
    storageBucket: 'task-management-apps-1.appspot.com',
    androidClientId: '860614070882-5lp3ekhrhnkn3u6mbje10esoih14lbe6.apps.googleusercontent.com',
    iosClientId: '860614070882-ognnjc3cvrnfmcdr34iass400cmnrthv.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbx_dFjmiWCcDizO_eNjJRhsL3bJ6OrCM',
    appId: '1:860614070882:ios:7025b23e509415cef0b73b',
    messagingSenderId: '860614070882',
    projectId: 'task-management-apps-1',
    storageBucket: 'task-management-apps-1.appspot.com',
    androidClientId: '860614070882-5lp3ekhrhnkn3u6mbje10esoih14lbe6.apps.googleusercontent.com',
    iosClientId: '860614070882-ognnjc3cvrnfmcdr34iass400cmnrthv.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp1',
  );
}
